# 使用傳送標誌時需要的物品（設為 none 代表不需要）
use-item: ENDER_PEARL

# 使用傳送標誌時消耗的物品數量
use-cost: 1

# 傳送前的冷卻時間（單位：秒）
teleport-delay: 5

# 設置傳送完成後的冷卻（單位：秒）
teleport-use-cooldown: 10

# 傳送時播放的音效
teleport-sound: minecraft:entity.enderman.teleport

# 傳送時顯示的效果
teleport-effect: ENDER_SIGNAL

###############################################################################
# 以下設定只影響建立 Warp Target (WPT) 標誌，WP 則免費建立
###############################################################################
# 建立 Warp Target 標誌所需的物品（設為 none 代表不需要）
create-wpt-item: "DIAMOND_SWORD"
# 建立 Warp Target 標誌時消耗的物品數量
create-wpt-item-cost: 1

###############################################################################
# 傳送點可見性設定
###############################################################################
# 預設的傳送點可見性（true 為私人，false 為公共）
default-visibility: false

###############################################################################
# 自訂訊息
###############################################################################
messages:
  create_permission: "&c您沒有權限建立傳送標誌！"
  no_warp_name: "&c未設定傳送名稱！\n請在第二行設定傳送名稱。"
  warp_created: "&a傳送標誌已成功建立。"
  warp_name_taken: "&c已有相同名稱的傳送目標！"
  warp_destroyed: "&a傳送目標已被摧毀。"
  target_sign_created: "&a傳送目標標誌已成功建立。"
  destroy_permission: "&c您沒有權限摧毀傳送標誌！"
  invalid_item: "&c您必須使用 {use-item} 來啟用此傳送！"
  not_enough_item: "&c您沒有足夠的 {use-item} x{use-cost} 來建立此傳送標誌。"
  warp_not_found: "&c指定的傳送目標不存在！"
  use_permission: "&c您沒有權限使用此傳送標誌！"
  teleport: "&e正在傳送到 {warp-name}，{time} 秒後到達..."
  teleport-success: "&a成功傳送到 {warp-name}。"
  teleport-cancelled: "&c傳送已取消。"
  notify-cost: "&a您已被收取 {cost} 金幣進行傳送。"
  not_permission: "&c您沒有權限！"
  cooldown: "&c您必須等待 {cooldown} 秒才能再次傳送。"
  private_warp: "&c這是一個私人傳送點，只有創建者可以使用。"
  warp_visibility_changed: "&a傳送點 {warp-name} 的可見性已更改為{visibility}。"
  cant_modify_others_warp: "&c您只能更改自己創建的傳送點！"
  set_visibility_usage: "&c用法: /wp set <public|private> <傳送點名稱>"
  invalid_visibility: "&c使用權限必須是 'public' 或 'private'"