# 使用傳送標誌時需要的物品（設為 none 代表不需要）
use-item: ENDER_PEARL

# 使用傳送標誌時消耗的物品數量
use-cost: 1

# 傳送前的冷卻時間（單位：秒）
teleport-delay: 5

# 設置傳送完成後的冷卻（單位：秒）
teleport-use-cooldown: 10

# 跨次元傳送設定
cross-dimension-teleport:
  # 是否允許跨次元傳送 (true 允許, false 禁止)
  enabled: true
  # OP 是否可以無視跨次元限制 (true 允許, false 禁止)
  op-bypass: true
# 群組功能相關設定
warp-groups:
  # 是否啟用群組功能
  enabled: true
  # 每位玩家最多可建立的群組數量
  max-groups-per-player: 5
  # 每個群組最多可包含的傳送點數量
  max-warps-per-group: 10
  # 每個群組最多可邀請的成員數量
  max-members-per-group: 20
  # 是否允許普通玩家使用群組功能（建議設為 true）
  allow-normal-players: true
###############################################################################
# 以下設定只影響建立 Warp Target (WPT) 標誌
###############################################################################
# 建立 Warp Target 標誌所需的物品（設為 none 代表不需要）
create-wpt-item: DIAMOND_SWORD
# 建立 Warp Target 標誌時消耗的物品數量
create-wpt-item-cost: 1
# 每位玩家最多可創建的傳送點數量（-1 表示無限制）
max-warps-per-player: 10
# OP 是否不受創建數量限制（true 表示 OP 無限制）
op-unlimited-warps: true
# 預設的傳送點可見性（true 為私人，false 為公共）
default-visibility: false
# 是否在 WPT 告示牌上顯示建立者資訊（true 表示顯示，false 表示不顯示）
show-creator-on-sign: true
###############################################################################
# 自訂訊息
###############################################################################
messages:
  create_permission: "&c您沒有權限建立傳送標誌！"
  no_warp_name: "&c未設定傳送名稱！\n請在第二行設定傳送名稱。"
  warp_created: "&a傳送標誌已成功建立。"
  warp_name_taken: "&c已有相同名稱的傳送目標！"
  warp_destroyed: "&a傳送目標已被摧毀。"
  target_sign_created: "&a傳送目標標誌已成功建立。"
  destroy_permission: "&c您沒有權限摧毀傳送標誌！"
  invalid_item: "&c您必須使用 {use-item} 來啟用此傳送！"
  not_enough_item: "&c您沒有足夠的 {use-item} x{use-cost} 來建立此傳送標誌。"
  warp_not_found: "&c指定的傳送目標不存在！"
  use_permission: "&c您沒有權限使用此傳送標誌！"
  teleport: "&e正在傳送到 {warp-name}，{time} 秒後到達..."
  teleport-success: "&a成功傳送到 {warp-name}。"
  teleport-cancelled: "&c傳送已取消。"
  notify-cost: "&a您已被收取 {cost} 金幣進行傳送。"
  not_permission: "&c您沒有權限！"
  cooldown: "&c您必須等待 {cooldown} 秒才能再次傳送。"
  warp_visibility_changed: "&a傳送點 {warp-name} 的使用權限已更改為{visibility}。"
  cant_modify_others_warp: "&c您只能更改自己創建的傳送點！"
  set_visibility_usage: "&c用法: /wp set <公共|私人> <傳送點名稱>"
  invalid_visibility: "&c使用權限必須是 '公共' 或 '私人'"
  private_warp: "&c這是一個私人傳送點，只有創建者和被邀請的玩家可以使用。"
  invite_success: "&a已成功邀請 {player} 使用傳送點 '{warp-name}'！"
  invite_received: "&a{inviter} 邀請你使用傳送點 '{warp-name}'！"
  invite_failed: "&c無法邀請玩家使用此傳送點！"
  uninvite_success: "&a已移除 {player} 使用傳送點 '{warp-name}' 的權限。"
  player_not_found: "&c找不到玩家 '{player}' 或該玩家離線！"
  not_your_warp: "&c你只能邀請玩家使用你自己的傳送點！"
  invite_usage: "&c用法: /wp invite <玩家> <傳送點名稱>"
  uninvite_usage: "&c用法: /wp uninvite <玩家> <傳送點名稱>"
  already_invited: "&c玩家 {player} 已經被邀請使用此傳送點！"
  not_invited: "&c玩家 {player} 未被邀請使用此傳送點。"
  invite_list: "&a傳送點 '{warp-name}' 的邀請列表:"
  no_invites: "&e此傳送點尚未邀請任何玩家。"
  cant_modify_warp: "&c您無法修改此傳送點的邀請名單！"
  warp_limit_reached: "&c您已達到最大傳送點創建數量限制 ({current}/{max})！"
  warp_count_info: "&a您目前已創建 {current} 個傳送點，限制為 {max} 個。"
  unlimited_warps: "&a您擁有無限制的傳送點創建權限。"
  my_warps_header: "&a=== {player}擁有的傳送點 ==="
  no_warps_owned: "&7{player}目前沒有擁有任何傳送點。"
  warp_list_format: "&f{index}. &b{warp-name} &7({visibility}) - &e{world} &7({x}, {y}, {z})"
  total_warps: "&a{player}總共擁有 {count} 個傳送點"
  not_permission_view_others: "&c您沒有權限查看其他玩家的傳送點！"
  player_not_found_or_no_warps: "&c找不到玩家 '{player}' 或該玩家沒有任何傳送點。"
  creator-display-format: "&7建立者: &f{creator}"
  cross_dimension_disabled: "&c跨次元傳送已被禁用！您無法傳送到位於 &e{target-world} &c世界的傳送點。"
  warp_world_not_found: "&c傳送點所在的世界不存在或未載入！請聯絡管理員。"
  player_not_online: "&c玩家 '{player}' 目前不在線上！請等待玩家上線後再進行操作。"
  group_created: "&a成功建立群組 '{group-name}'！"
  group_deleted: "&a群組 '{group-name}' 已刪除。"
  warp_added_to_group: "&a傳送點 '{warp-name}' 已加入群組 '{group-name}'。"
  warp_removed_from_group: "&a傳送點 '{warp-name}' 已從群組 '{group-name}' 中移除。"
  player_invited_to_group: "&a玩家 '{player}' 已被邀請加入群組 '{group-name}'。"
  player_removed_from_group: "&a玩家 '{player}' 已從群組 '{group-name}' 中移除。"
  group_not_found: "&c找不到群組 '{group-name}'。"
  not_group_owner: "&c您不是此群組的擁有者！"
  warp_not_private: "&c只有私人傳送點才能加入群組！"
  warp_already_in_group: "&c傳送點 '{warp-name}' 已經在群組 '{existing-group}' 中。"
  max_groups_reached: "&c您已達到群組建立上限！"
  no_permission_use_warp: "&c您沒有權限使用此傳送點！"
  teleport_success: "&a成功傳送到 '{warp-name}'！"
  teleport_failed: "&c傳送失敗，請稍後再試。"
  group_help_header: "&a=== SignWarp 群組指令說明 ==="
  group_help_create: "&b/wp group create <群組名稱> &7- 建立新群組"
  group_help_list: "&b/wp group list &7- 查看您的群組列表"
  group_help_info: "&b/wp group info <群組名稱> &7- 查看群組詳細資訊"
  group_help_add: "&b/wp group add <群組名稱> <傳送點> &7- 將傳送點加入群組"
  group_help_remove: "&b/wp group remove <群組名稱> <傳送點> &7- 從群組移除傳送點"
  group_help_invite: "&b/wp group invite <群組名稱> <玩家> &7- 邀請玩家加入群組"
  group_help_uninvite: "&b/wp group uninvite <群組名稱> <玩家> &7- 移除群組成員"
  group_help_delete: "&b/wp group delete <群組名稱> &7- 刪除群組"