name: SignWarp
version: '${project.version}'
description: Warp tp plugin on signs
author: Swim
website: https://verdo568.vercel.app/
api-version: '1.21'
main: com.swim.signwarp.SignWarp
commands:
  signwarp:
    description: "Manage SignWarp commands"
    usage: "/signwarp <subcommand>"
    aliases: ["wp"]
permissions:
  signwarp.*:
    children:
      - signwarp.create
      - signwarp.use
      - signwarp.destroy
  signwarp.create:
    description: "Allows you to create warp signs"
    default: op
  signwarp.use:
    description: "Allow uses of warp signs"
    default: true
  signwarp.reload:
    description: "Allows you to reload the SignWarp configuration"
    default: op
  signwarp.admin:
    description: "Allows access to the warp management GUI"
    default: op
  signwarp.destroy:
    description: "Allows you to destroy warp signs"
    default: op